#!/usr/bin/env python
# coding: utf-8

from sys import exit

password = raw_input('Enter the user\'s new password: ')
confirmation = raw_input('Please type it again for verification: ')

if password == confirmation:
    print('Password has been changed successfully')
    exit(0)
else:
    print('Passwords didn\'t match')
    exit(5)
